title: Everyday Learning Analytics @ Vihula Winter School (13.01.2017)
author: Luis P. Prieto
email: lprisan@hotmail.com
description: A prototype of what Everyday Learning Analytics might look like
baseurl: /EverydayLA-Prototype3

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
